In [1]:
import pandas as pd
import numpy as np

### Vulnerability EDA

In [ ]:
vul = pd.read_cev(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\HP\flood-data-ecosystem-Himachal-Pradesh\RiskScoreModel\data\MASTER_VARIABLES.csv')

## Edits to MASTER_VARIABLES

In [2]:
master = pd.read_csv(r'D:\CivicDataLabs_IDS-DRR\IDS-DRR_Github\HP\flood-data-ecosystem-Himachal-Pradesh\RiskScoreModel\data\MASTER_VARIABLES.csv')

In [4]:
master['dtcode11_x'] = master['dtcode11_x'].astype(str).apply(lambda x: x.zfill(2))
master['sdtcode11'] = master['sdtcode11'].astype(str).apply(lambda x: x.zfill(5))
master['object_id'] = master.apply(lambda row: f"02-{row['dtcode11_x']}-{row['sdtcode11']}", axis=1)

In [6]:
master

,sdtcode11,district,dtcode11_x,rc_area,timeperiod,total_tender_awarded_value,Others_tenders_awarded_value,Unnamed: 0,objectid_x,stcode11,...,district_name,sub_district_name,sub_district_code,net_sown_area_in_hac,avg_electricity,avg_tele,sd_piped_hhds_pct,sd_nosanitation_hhds_pct,total_hhd,object_id
0,00088,Chamba,23,3.695661e+08,2021_04,0.0,0.0,0.0,0.0,0.0,...,CHAMBA,Bhattiyat,88.0,3371.35,6.67,3.0,37.72,7.10,8768.0,02-23-00088
1,00092,Chamba,23,1.334739e+09,2021_04,0.0,0.0,0.0,0.0,0.0,...,CHAMBA,Brahmaur,92.0,2441.91,6.67,3.0,49.17,9.48,11464.0,02-23-00092
2,00090,Chamba,23,1.422634e+09,2021_04,0.0,0.0,0.0,0.0,0.0,...,CHAMBA,Chamba,90.0,15979.67,4.43,3.0,29.82,3.10,31915.0,02-23-00090
3,00084,Chamba,23,1.652463e+09,2021_04,0.0,0.0,0.0,0.0,0.0,...,CHAMBA,Chaurah,84.0,20584.07,4.38,3.0,27.43,7.22,21173.0,02-23-00084
4,00087,Chamba,23,2.287591e+08,2021_04,0.0,0.0,0.0,0.0,0.0,...,CHAMBA,Dalhousie,87.0,1570.30,6.17,2.0,37.40,5.36,12671.0,02-23-00087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,00183,Shimla,33,1.504535e+08,2024_08,0.0,0.0,0.0,0.0,0.0,...,SHIMLA,Junga,183.0,683.29,3.42,3.0,34.52,14.85,3486.0,02-33-00183
5039,00176,Sirmaur,32,1.341459e+08,2024_08,0.0,0.0,0.0,0.0,0.0,...,SIRMAUR,Ronhat,176.0,3057.69,3.50,3.0,21.88,7.90,5732.0,02-32-00176
5040,00130,Mandi,27,1.077063e+08,2024_08,0.0,0.0,0.0,0.0,0.0,...,MANDI,Bhadrota,130.0,1745.49,4.04,2.0,68.76,0.25,7510.0,02-27-00130
5041,00147,Una,29,1.361356e+08,2024_08,0.0,0.0,0.0,0.0,0.0,...,UNA,Bharwain,147.0,1574.02,3.92,2.0,67.62,0.21,5234.0,02-29-00147
5042,00135,Mandi,27,2.698807e+08,2024_08,0.0,0.0,0.0,0.0,0.0,...,MANDI,Bali Chowki,135.0,5887.67,5.34,2.0,33.60,1.90,12978.0,02-27-00135

In [8]:
master.drop(['Unnamed: 0','objectid_x', 'stcode11', 'dtcode11_x', 'dtcode11_y', 'stname','dtname','sdtname','subdt_lgd','state_lgd','dist_lgd','st_area_sh','st_length_','test','st_area(shape)','st_length(shape)'
                           ],axis=1).to_csv(r'D:\CivicDataLabs_IDS-DRR\IDS-DRR_Github\HP\flood-data-ecosystem-Himachal-Pradesh\RiskScoreModel\data\MASTER_VARIABLES.csv', index=False)

## Convert risk_score_final.csv sdtcode11 back to string

In [12]:
riskscore = pd.read_csv(r'D:\CivicDataLabs_IDS-DRR\IDS-DRR_Github\HP\flood-data-ecosystem-Himachal-Pradesh\RiskScoreModel\data\risk_score_final_hp.csv')
riskscore['sdtcode11'] = riskscore['sdtcode11'].apply(lambda x: f"{int(float(x)) :05d}" if pd.notna(x) and x != '' else '')

In [17]:
riskscore

,sdtcode11,district,rc-area,timeperiod,total-tender-awarded-value,others-tenders-awarded-value,remarks,ac-no,max-rain,mean-rain,...,sd-nosanitation-hhds-pct,total-hhd,object-id,exposure,flood-hazard,government-response,vulnerability,topsis-score,risk-score,Unnamed: 0
0,00098,Kangra,3.426532e+08,2021_04,0.0,0.0,0.0,0.0,0.452112,0.435882,...,16.74,18015.0,02-24-00098,2,3.0,5,3,0.709431,5,NaN
1,00171,Sirmaur,1.788162e+08,2021_04,0.0,0.0,0.0,0.0,0.387721,0.284196,...,4.43,9548.0,02-32-00171,1,2.0,5,5,0.544420,4,NaN
2,00168,Sirmaur,2.493992e+08,2021_04,0.0,0.0,0.0,0.0,0.301307,0.266202,...,12.73,6535.0,02-32-00168,1,2.0,5,5,0.544420,4,NaN
3,00093,Kangra,7.573396e+08,2021_04,0.0,0.0,0.0,0.0,0.336361,0.264498,...,12.57,39960.0,02-24-00093,4,2.0,5,3,0.527438,4,NaN
4,00173,Sirmaur,9.913454e+08,2021_04,0.0,0.0,0.0,0.0,0.417084,0.294889,...,4.66,35307.0,02-32-00173,4,2.0,5,3,0.527438,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5530,,Una,NaN,2024_04,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29,4,1.0,5,1,NaN,1,9.0
5531,,Una,NaN,2024_05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29,4,1.0,5,1,NaN,1,9.0
5532,,Una,NaN,2024_06,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29,4,1.0,5,1,NaN,1,9.0
5533,,Una,NaN,2024_07,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29,4,1.0,5,1,NaN,1,9.0
5534,,Una,NaN,2024_08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,29,4,1.0,1,1,NaN,1,9.0

In [19]:
riskscore.drop(['Unnamed: 0','remarks','ac-no'
                           ],axis=1).to_csv(r'D:\CivicDataLabs_IDS-DRR\IDS-DRR_Github\HP\flood-data-ecosystem-Himachal-Pradesh\RiskScoreModel\data\risk_score_final_hp.csv', index=False)

## Edits to risk_score.csv

In [14]:
risk_score = pd.read_csv(r'D:\CivicDataLabs_IDS-DRR\IDS-DRR_Github\HP\flood-data-ecosystem-Himachal-Pradesh\RiskScoreModel\data\risk_score_renamed.csv')
risk_score

,sdtcode11,district,rc-area,timeperiod,total-tender-awarded-value,others-tenders-awarded-value,unnamed:-0,objectid-x,stcode11,dtcode11,...,roads,bridge,embankment-breached,relief-camp-inmates,human-live-lost,sexratio,sum-aged-population,sum-young-population,sum-population,drainage-density
0,173.0,Sirmaur,9.913454e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.93,16899.547170,86846.829690,355691.562500,0.000541
1,93.0,Kangra,7.573396e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.94,40603.369140,140334.732800,737687.131300,0.000509
2,172.0,Sirmaur,3.936043e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.94,17413.600000,72495.879690,326873.256300,0.000640
3,103.0,Kangra,7.508755e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.94,13713.774800,56979.931250,256952.904700,0.000613
4,95.0,Kangra,3.879163e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.95,16755.950200,66634.473830,325031.925000,0.000611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0.95,7.991751,27.313598,153.984912,0.000719
5216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0.93,963.763879,3846.440283,17933.489260,0.000690
5217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0.94,9528.750342,28154.628910,178280.451600,0.000651
5218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,0,0,0,0,0.94,10079.158980,36715.096480,168445.135900,0.000539
5219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0.93,9397.514893,38025.350780,175594.070300,0.000521

In [15]:
risk_score = risk_score[risk_score['sdtcode11'].notna()]
risk_score

,sdtcode11,district,rc-area,timeperiod,total-tender-awarded-value,others-tenders-awarded-value,unnamed:-0,objectid-x,stcode11,dtcode11,...,roads,bridge,embankment-breached,relief-camp-inmates,human-live-lost,sexratio,sum-aged-population,sum-young-population,sum-population,drainage-density
0,173.0,Sirmaur,9.913454e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.93,16899.547170,86846.829690,355691.56250,0.000541
1,93.0,Kangra,7.573396e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.94,40603.369140,140334.732800,737687.13130,0.000509
2,172.0,Sirmaur,3.936043e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.94,17413.600000,72495.879690,326873.25630,0.000640
3,103.0,Kangra,7.508755e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.94,13713.774800,56979.931250,256952.90470,0.000613
4,95.0,Kangra,3.879163e+08,2021_04,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0.95,16755.950200,66634.473830,325031.92500,0.000611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3562,114.0,Lahul And Spiti,2.575013e+09,2023_08,0.0,0.0,69.0,3311.0,2.0,25.0,...,0,0,0,0,0,0.90,1446.143774,6671.192285,34245.97188,0.000247
3563,182.0,Shimla,2.384353e+07,2023_08,0.0,0.0,71.0,3316.0,2.0,33.0,...,0,0,0,0,0,0.94,8692.978125,33120.042580,157610.28750,0.000646
3564,194.0,Kinnaur,7.109808e+08,2023_08,0.0,0.0,73.0,1703.0,2.0,34.0,...,0,0,0,0,0,0.94,9496.716504,36321.323440,171725.08750,0.000661
3565,157.0,Bilaspur,1.454353e+08,2023_08,0.0,0.0,81.0,2108.0,2.0,30.0,...,0,0,0,0,0,0.93,5685.684082,28148.282030,116066.88280,0.000518
3566,177.0,Shimla,1.166556e+09,2023_08,0.0,0.0,42.0,43.0,2.0,33.0,...,0,0,0,0,0,0.91,3085.269922,14238.190630,72981.88594,0.000247

In [16]:
risk_score = risk_score.drop(['unnamed:-0','objectid-x','remarks','ac-no','test','objectid-y','object-id'],axis=1)
risk_score

,sdtcode11,district,rc-area,timeperiod,total-tender-awarded-value,others-tenders-awarded-value,stcode11,dtcode11,stname,dtname,...,roads,bridge,embankment-breached,relief-camp-inmates,human-live-lost,sexratio,sum-aged-population,sum-young-population,sum-population,drainage-density
0,173.0,Sirmaur,9.913454e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.93,16899.547170,86846.829690,355691.56250,0.000541
1,93.0,Kangra,7.573396e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.94,40603.369140,140334.732800,737687.13130,0.000509
2,172.0,Sirmaur,3.936043e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.94,17413.600000,72495.879690,326873.25630,0.000640
3,103.0,Kangra,7.508755e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.94,13713.774800,56979.931250,256952.90470,0.000613
4,95.0,Kangra,3.879163e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.95,16755.950200,66634.473830,325031.92500,0.000611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3562,114.0,Lahul And Spiti,2.575013e+09,2023_08,0.0,0.0,2.0,25.0,HIMACHAL PRADESH,Lahul And Spiti,...,0,0,0,0,0,0.90,1446.143774,6671.192285,34245.97188,0.000247
3563,182.0,Shimla,2.384353e+07,2023_08,0.0,0.0,2.0,33.0,HIMACHAL PRADESH,Shimla,...,0,0,0,0,0,0.94,8692.978125,33120.042580,157610.28750,0.000646
3564,194.0,Kinnaur,7.109808e+08,2023_08,0.0,0.0,2.0,34.0,HIMACHAL PRADESH,Kinnaur,...,0,0,0,0,0,0.94,9496.716504,36321.323440,171725.08750,0.000661
3565,157.0,Bilaspur,1.454353e+08,2023_08,0.0,0.0,2.0,30.0,HIMACHAL PRADESH,Bilaspur,...,0,0,0,0,0,0.93,5685.684082,28148.282030,116066.88280,0.000518
3566,177.0,Shimla,1.166556e+09,2023_08,0.0,0.0,2.0,33.0,HIMACHAL PRADESH,Shimla,...,0,0,0,0,0,0.91,3085.269922,14238.190630,72981.88594,0.000247

In [25]:
risk_score['sdtcode11'] = risk_score['sdtcode11'].apply(lambda x: str(int(float(x))).zfill(5))
risk_score

,sdtcode11,district,rc-area,timeperiod,total-tender-awarded-value,others-tenders-awarded-value,stcode11,dtcode11,stname,dtname,...,roads,bridge,embankment-breached,relief-camp-inmates,human-live-lost,sexratio,sum-aged-population,sum-young-population,sum-population,drainage-density
0,00173,Sirmaur,9.913454e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.93,16899.547170,86846.829690,355691.56250,0.000541
1,00093,Kangra,7.573396e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.94,40603.369140,140334.732800,737687.13130,0.000509
2,00172,Sirmaur,3.936043e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.94,17413.600000,72495.879690,326873.25630,0.000640
3,00103,Kangra,7.508755e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.94,13713.774800,56979.931250,256952.90470,0.000613
4,00095,Kangra,3.879163e+08,2021_04,0.0,0.0,0.0,0.0,0,0,...,0,0,0,0,0,0.95,16755.950200,66634.473830,325031.92500,0.000611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3562,00114,Lahul And Spiti,2.575013e+09,2023_08,0.0,0.0,2.0,25.0,HIMACHAL PRADESH,Lahul And Spiti,...,0,0,0,0,0,0.90,1446.143774,6671.192285,34245.97188,0.000247
3563,00182,Shimla,2.384353e+07,2023_08,0.0,0.0,2.0,33.0,HIMACHAL PRADESH,Shimla,...,0,0,0,0,0,0.94,8692.978125,33120.042580,157610.28750,0.000646
3564,00194,Kinnaur,7.109808e+08,2023_08,0.0,0.0,2.0,34.0,HIMACHAL PRADESH,Kinnaur,...,0,0,0,0,0,0.94,9496.716504,36321.323440,171725.08750,0.000661
3565,00157,Bilaspur,1.454353e+08,2023_08,0.0,0.0,2.0,30.0,HIMACHAL PRADESH,Bilaspur,...,0,0,0,0,0,0.93,5685.684082,28148.282030,116066.88280,0.000518
3566,00177,Shimla,1.166556e+09,2023_08,0.0,0.0,2.0,33.0,HIMACHAL PRADESH,Shimla,...,0,0,0,0,0,0.91,3085.269922,14238.190630,72981.88594,0.000247

In [29]:
risk_score = risk_score.drop(['stname','dtname','dtcode11','sdtname','stcode11','sdtname','subdt-lgd','dist-lgd','state-lgd'],axis=1)

In [30]:
risk_score.to_csv(r'D:\CivicDataLabs_IDS-DRR\IDS-DRR_Github\HP\flood-data-ecosystem-Himachal-Pradesh\RiskScoreModel\data\risk_score_cleaned.csv')